import type { AuthoredTab } from '@/types/nav'

// English sidebar labels. Mirrors navigation.ja.ts one-for-one: SAME routes and
// SAME structure, translated titles only. Keep the two files in lock-step — a
// route added to one must be added to the other. basePath stays locale-neutral
// ("/guide"); the locale prefix is applied at build time in lib/nav.ts.
export const navigation: AuthoredTab[] = [
  {
    id: 'learn',
    title: 'Learn',
    basePath: '/guide',
    parts: [
      {
        id: 'setup',
        no: 1,
        title: 'Setup & creating a project',
        items: [
          { route: 'setup/goal', title: 'Goal of this part' },
          { route: 'setup/node-npm-npx', title: 'What are Node.js / npm / npx' },
          { route: 'setup/terminal', title: 'Opening the terminal' },
          { route: 'setup/check-node', title: 'Check whether it is installed' },
          { route: 'setup/install-node', title: 'If it is not installed (installing)' },
          { route: 'setup/why-vite', title: 'Why Vite' },
          { route: 'setup/create-vite', title: 'Running npm create vite' },
          { route: 'setup/project-name', title: 'Choice 1: project name and framework' },
          { route: 'setup/variants', title: 'Choice 2: every variant explained' },
          { route: 'setup/react-compiler', title: 'What is the React Compiler' },
          { route: 'setup/typescript-intro', title: 'What is TypeScript (a light intro)' },
          { route: 'setup/vite-vs-next', title: 'How it differs from create-next-app' },
          { route: 'setup/open-vscode', title: 'Opening it in VS Code' },
          { route: 'setup/npm-install', title: 'What npm install actually does' },
          { route: 'setup/npm-run-dev', title: 'Starting the dev server with npm run dev' },
          { route: 'setup/generated-files', title: 'Reading the generated files one by one' },
          { route: 'setup/first-edit', title: 'Your first edit (HMR)' },
          { route: 'setup/blank-slate', title: 'Clearing the defaults to a blank slate' },
          { route: 'setup/path-alias', title: 'Shortening relative paths with the @/ alias' },
          { route: 'setup/vscode-settings', title: 'VS Code settings' },
          { route: 'setup/troubleshooting', title: 'When things go wrong' },
          { route: 'setup/summary', title: 'Summary & exercises' },
        ],
      },
      {
        id: 'javascript',
        no: 2,
        title: 'JavaScript you need before React',
        items: [
          { route: 'javascript/const-let', title: 'const and let' },
          { route: 'javascript/values-and-types', title: 'Values and types' },
          { route: 'javascript/objects-arrays', title: 'Objects and arrays basics' },
          { route: 'javascript/arrow-functions', title: 'Arrow functions' },
          { route: 'javascript/template-literals', title: 'Template literals' },
          { route: 'javascript/strings', title: 'Working with strings' },
          { route: 'javascript/destructuring', title: 'Destructuring' },
          { route: 'javascript/spread-rest', title: 'Spread and rest' },
          { route: 'javascript/array-methods', title: 'map / filter / find' },
          { route: 'javascript/loops', title: 'Loops' },
          { route: 'javascript/truthy-falsy', title: 'truthy and falsy' },
          { route: 'javascript/equality', title: 'Equality (=== and ==)' },
          { route: 'javascript/ternary-short-circuit', title: 'Ternary and short-circuit' },
          { route: 'javascript/optional-chaining', title: '?. and ??' },
          { route: 'javascript/symbols', title: 'Reading the symbols (! !! % ===)' },
          { route: 'javascript/functions-as-values', title: 'Passing functions as values' },
          { route: 'javascript/reference-vs-copy', title: 'Reference vs copy' },
          { route: 'javascript/import-export', title: 'import and export' },
          { route: 'javascript/json', title: 'JSON' },
          { route: 'javascript/promise-async-await', title: 'Promise and async / await' },
          { route: 'javascript/not-yet', title: 'What you can skip for now' },
        ],
      },
      {
        id: 'components',
        no: 3,
        title: 'Your first React',
        items: [
          { route: 'components/goal', title: 'Goal of this part' },
          { route: 'components/jsx', title: 'JSX: JavaScript that looks like HTML' },
          { route: 'components/first-component', title: 'Building your first component' },
          { route: 'components/props', title: 'Receiving values with props' },
          { route: 'components/rendering-lists', title: 'Rendering lists with map' },
          { route: 'components/conditional', title: 'Conditional rendering' },
          { route: 'components/events', title: 'Responding to clicks (events)' },
          { route: 'components/button-variants', title: 'Reusing with variants' },
          { route: 'components/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'state',
        no: 4,
        title: 'State and hooks',
        items: [
          { route: 'state/goal', title: 'Goal of this part' },
          {
            group: 'useState',
            pages: [
              { route: 'state/use-state/what-is-state', title: 'What is state' },
              { route: 'state/use-state/basics', title: 'useState basics' },
              { route: 'state/use-state/events', title: 'Changing state on events' },
              {
                route: 'state/use-state/updating-objects',
                title: 'Updating object state',
              },
              {
                route: 'state/use-state/updating-array-state',
                title: 'Updating array state',
              },
              {
                route: 'state/use-state/functional-updates',
                title: 'Updating from the previous value',
              },
            ],
          },
          {
            group: 'useEffect',
            pages: [{ route: 'state/use-effect/basics', title: 'What is useEffect (side effects)' }],
          },
          { route: 'state/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'styling',
        no: 5,
        title: 'Styling (SCSS Modules)',
        items: [
          { route: 'styling/goal', title: 'Goal of this part' },
          { route: 'styling/why-scss-modules', title: 'Why SCSS Modules' },
          { route: 'styling/first-module', title: 'Your first .module.scss' },
          { route: 'styling/scss-features', title: 'SCSS features (nesting, variables, mixins)' },
          { route: 'styling/design-tokens-theming', title: 'Design tokens and theming' },
          { route: 'styling/responsive', title: 'Responsive' },
          { route: 'styling/shared-mixin', title: 'Using our shared mixins (getVw, mq)' },
          { route: 'styling/conditional-classes', title: 'Conditional classes (clsx)' },
          { route: 'styling/project', title: 'Capstone: finishing the list' },
          { route: 'styling/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'typescript',
        no: 6,
        title: 'TypeScript for React',
        items: [
          { route: 'typescript/goal', title: 'Goal of this part' },
          { route: 'typescript/basic-types', title: 'Basic types' },
          { route: 'typescript/interface', title: 'Describing object shapes with interface' },
          { route: 'typescript/typing-props', title: 'Typing props' },
          { route: 'typescript/union-literal', title: 'Union and literal types' },
          { route: 'typescript/product-type', title: 'The Product type and data' },
          { route: 'typescript/typing-state-events', title: 'Typing state and events' },
          { route: 'typescript/project', title: 'Capstone: guarding ProductCard with types' },
          { route: 'typescript/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'routing',
        no: 7,
        title: 'Routing',
        items: [
          { route: 'routing/goal', title: 'Goal of this part' },
          { route: 'routing/setup-router', title: 'Setting up the router' },
          { route: 'routing/link', title: 'Navigating with Link' },
          { route: 'routing/route-params', title: 'URL params (product detail)' },
          { route: 'routing/layout-outlet', title: 'Shared layout and Outlet' },
          { route: 'routing/navigate', title: 'Navigating in code (useNavigate)' },
          { route: 'routing/project', title: 'Capstone: a multi-page app' },
          { route: 'routing/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'data',
        no: 8,
        title: 'Data fetching',
        items: [
          { route: 'data/goal', title: 'Goal of this part' },
          { route: 'data/from-json-to-fetch', title: 'From direct import to fetch' },
          { route: 'data/fetch-basics', title: 'fetch basics' },
          { route: 'data/useeffect-fetch', title: 'Fetching with useEffect' },
          { route: 'data/three-states', title: 'The three states: loading, error, success' },
          { route: 'data/custom-hook', title: 'Extracting a useProducts custom hook' },
          { route: 'data/project', title: 'Capstone: fetch the list' },
          { route: 'data/summary', title: 'Summary & practice' },
        ],
      },
    ],
  },
  {
    id: 'libraries',
    title: 'Libraries',
    basePath: '/libraries',
    parts: [
      {
        id: 'library-basics',
        title: 'Working with libraries',
        items: [
          { route: 'libraries/goal', title: 'Intro — working with libraries' },
          { route: 'libraries/npm-install-writes', title: 'What npm install changes' },
          { route: 'libraries/choosing', title: 'How to choose a library' },
          { route: 'libraries/types-packages', title: 'Types in separate packages (@types/*)' },
          { route: 'libraries/sass', title: 'Adding sass' },
          { route: 'libraries/clsx', title: 'Building class names with clsx' },
          { route: 'libraries/react-router', title: 'Adding react-router' },
          { route: 'libraries/motion', title: 'Adding motion' },
          { route: 'libraries/env', title: 'Environment variables: .env and VITE_' },
          { route: 'libraries/managing', title: 'Removing, swapping, upgrading' },
        ],
      },
      {
        id: 'framer-motion',
        title: 'Framer Motion (motion)',
        items: [
          { route: 'libraries/framer-motion/goal', title: 'Goal of this part' },
          { route: 'libraries/framer-motion/motion-basics', title: 'motion basics' },
          { route: 'libraries/framer-motion/interaction', title: 'Responding to hover and tap' },
          { route: 'libraries/framer-motion/reduced-motion', title: 'Respecting reduced-motion settings' },
          {
            route: 'libraries/framer-motion/scroll-and-stagger',
            title: 'Reveal on scroll and stagger',
          },
          { route: 'libraries/framer-motion/exit', title: 'Enter/exit animation (AnimatePresence)' },
          { route: 'libraries/framer-motion/project', title: 'Capstone: animating the list' },
          { route: 'libraries/framer-motion/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'gsap',
        title: 'GSAP',
        items: [
          { route: 'libraries/gsap/goal', title: 'Goal of this part' },
          { route: 'libraries/gsap/install', title: 'Adding gsap and @gsap/react' },
          { route: 'libraries/gsap/usegsap', title: 'Animating with useGSAP' },
          { route: 'libraries/gsap/timeline', title: 'Sequencing with a timeline' },
          {
            route: 'libraries/gsap/scrolltrigger',
            title: 'Syncing to scroll with ScrollTrigger',
          },
          { route: 'libraries/gsap/fm-vs-gsap', title: 'Framer Motion or GSAP — which one?' },
          { route: 'libraries/gsap/summary', title: 'Summary & practice' },
        ],
      },
      {
        id: 'swiper',
        title: 'Swiper (slider)',
        items: [
          { route: 'libraries/swiper/goal', title: 'Goal of this part' },
          { route: 'libraries/swiper/install', title: 'Adding swiper' },
          { route: 'libraries/swiper/basics', title: 'Building with Swiper and SwiperSlide' },
          { route: 'libraries/swiper/modules', title: 'Adding features with modules' },
          { route: 'libraries/swiper/project', title: 'A product carousel with breakpoints' },
          { route: 'libraries/swiper/summary', title: 'Summary & practice' },
        ],
      },
    ],
  },
  { id: 'project', title: 'Capstone', basePath: '/project', parts: [] },
  {
    id: 'recipes',
    title: 'Recipes',
    basePath: '/recipes',
    parts: [
      {
        id: 'recipes',
        title: 'Recipes',
        items: [
          { route: 'recipes/modal', title: 'Modal' },
          { route: 'recipes/accordion', title: 'Accordion' },
          { route: 'recipes/tabs', title: 'Tabs' },
          { route: 'recipes/range-slider', title: 'Range slider' },
          { route: 'recipes/copy-button', title: 'Copy button' },
          { route: 'recipes/scroll-reveal', title: 'Scroll reveal' },
          { route: 'recipes/tooltip', title: 'Tooltip' },
          { route: 'recipes/drawer', title: 'Drawer / hamburger' },
          { route: 'recipes/custom-select', title: 'Custom select' },
          { route: 'recipes/carousel', title: 'Carousel' },
          { route: 'recipes/star-rating', title: 'Star rating' },
          { route: 'recipes/toast', title: 'Toast notification' },
          { route: 'recipes/back-to-top', title: 'Back to top' },
        ],
      },
    ],
  },
  { id: 'standards', title: 'Standards', basePath: '/standards', parts: [] },
]
