// English chrome strings. Mirror of strings.ja.ts — the shape MUST match (the
// Strings type is inferred from the Japanese file in config/strings.ts).
export const strings = {
  langName: 'English',
  search: {
    open: 'Search',
    placeholder: 'Search pages and headings…',
    empty: 'No matches',
    hint: '↑↓ to move · Enter to open · Esc to close',
  },
  nav: {
    menu: 'Navigation',
    close: 'Close',
    onThisPage: 'On this page',
    prev: 'Previous',
    next: 'Next',
    prerequisites: 'Prerequisites',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    tabsAria: 'Sections',
    guideToc: 'Guide contents',
    prevNextAria: 'Previous and next pages',
    sectionsSuffix: 'sections',
  },
  theme: {
    toLight: 'Switch to light theme',
    toDark: 'Switch to dark theme',
  },
  page: {
    learnHeading: 'What you will learn',
    summaryHeading: 'Summary',
    exerciseHeading: 'Exercises',
    showAnswer: 'Show answer',
    showHint: 'Show hint',
    togetherHeading: "Let's try it together",
    partIntroHeading: 'Before you start this part',
    minutesLabel: 'Reading time',
    loading: 'Loading…',
    markRead: 'Mark as read',
    markedRead: 'Read ✓',
    feedbackLead: 'Was this page hard to follow?',
    feedbackLink: 'Tell us what tripped you up',
    readingTime: (n: number) => `${n} min read`,
    readingShort: (n: number) => `${n} min`,
  },
  progress: {
    overall: 'Overall progress',
    unit: 'pages',
  },
  reset: {
    part: 'Reset read state for this part',
    all: 'Reset all progress',
    confirmTitle: 'Clear all your read history?',
    confirmBody: 'This cannot be undone. Every page you have marked as read will be forgotten.',
    cancel: 'Cancel',
    confirmOk: 'Clear everything',
  },
  notFound: {
    title: 'Page not found',
    body: 'The URL may have changed, or this page has not been written yet.',
    back: '← Back to home',
  },
  error: {
    title: 'Something went wrong',
    body: 'An error occurred while loading this page. Try reloading, or go back to the home page.',
    reload: 'Reload',
    back: '← Back to home',
  },
  callout: {
    note: 'Note',
    warn: 'Gotcha',
    mistake: 'Common mistake',
    analogy: 'Analogy',
    stdPill: 'Our standard',
    stdAltDefault: 'When to choose otherwise',
    deeperTag: 'Deeper',
    jsNoteTag: 'JS refresher',
    jsNoteMore: 'Learn more →',
  },
  mdx: {
    demoLabel: 'Live demo',
    demoReset: 'Reset',
    demoSource: 'Source code (click to toggle)',
    copy: 'Copy',
    copied: 'Copied',
  },
  home: {
    heroLine1: 'For everyone the official docs lost along the way:',
    heroLine2: 'a practical guide to React.',
    lead: 'Decide which tool to use before worrying about how to write it. A guided path — following our house standards — to writing components yourself instead of leaning on AI.',
    resume: 'Resume reading',
    start: 'Get started',
    fromStart: 'From the start',
    searchHintPre: 'or',
    searchHintPost: 'to search',
    lastNote: 'Where you left off: ',
    pathsTitle: 'How to read this',
    paths: [
      {
        title: 'The big picture in a day',
        body: 'Get a feel for what React actually does for you. Where you start depends on how confident you are with JS.',
        links: [
          { label: 'Shaky on JS? Start here: destructuring', to: '/guide/javascript/destructuring' },
          { label: 'Comfortable with JS? Start here: reusing with variants', to: '/guide/components/button-variants' },
        ],
      },
      {
        title: 'Writing React in a week',
        body: 'Component → props → state, hands-on and in order.',
        links: [
          { label: 'Reusing with variants', to: '/guide/components/button-variants' },
          { label: 'Updating array state', to: '/guide/state/use-state/updating-array-state' },
        ],
      },
      {
        title: 'Look things up as you need them',
        body: 'Work backwards from "I want to build this." Recipes and search (Ctrl+K) are your way in.',
        links: [{ label: 'How to build a modal', to: '/recipes/modal' }],
      },
      {
        title: 'Already set up?',
        body: 'If Node and npm (or pnpm) are already installed, feel free to skip Part 1.',
        links: [
          { label: 'Start from npm create vite', to: '/guide/setup/create-vite' },
          { label: 'Know the setup? Jump to Part 2 (JavaScript)', to: '/guide/javascript/const-let' },
        ],
      },
    ],
  },
}
